config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'

  get 'pages/about'

  get 'pages/contact'

    root 'pages#home'
    get 'about', to:'pages#about'
    get 'contact', to:'pages#contact'
  
    resources :'articles'
    

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  validates :title, presence: true, length: { minimum: 5, maximum: 50 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
  validates :user_id, presence:true
end

app/models/article_category.rb
class ArticleCategory < ActiveRecord::Base
  belongs_to :article
  belongs_to :category
  
#   validates :title, presence: true, length: { minimum: 5, maximum: 50 }
#   validates :description, presence: true, length: { minimum: 10, maximum: 300 }
#   validates :user_id, presence: true
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :articles
    before_save { self.email  = email.downcase }
    validates :username, presence:true, uniqueness:{case_sensitive: false}, length: {minimum: 3, maximum: 25}
    VALID_EMAIL_REGEX= /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
    validates :email, presence:true, uniqueness:{case_sensitive: false}, length: {maximum: 105},format: {with: VALID_EMAIL_REGEX }
end

app/models/users.rb
class User < ActiveRecord::Base
    has_many :articles
    before_save { self.email  = email.downcase }
    validates :username, presence:true, uniqueness:{case_sensitive: false}, length: {minimum: 3, maximum: 25}
    VALID_EMAIL_REGEX:/\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
    validates :email, presence:true, uniqueness:{case_sensitive: false}, length: {maximum: 105},
    format: {with: VALID_EMAIL_REGEX }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:edit, :update, :show, :destroy]  
  def index
    @articles = Article.all
  end
  def new
    @article = Article.new   
  end
  def create
    @article = Article.new(article_params)
    if @article.save
        flash[:success] = "Article was succesfully created."
        redirect_to article_path(@article)
    else
        render 'new'
    end
  end    
  def edit    
  end
  def update
    if @article.update(article_params)
        flash[:info] = "Article was succesfully updated."
        redirect_to article_path(@article)
    else
        render 'edit'
    end
  end
  def show
  end
  def destroy
    @article.destroy
      flash[:danger] = "The selected article was deleted."
    redirect_to articles_path
  end

  private
    def article_params
      params.require(:article).permit(:title,:description)
    end
    def set_article
      @article = Article.find(params[:id])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
    when :notice then "alert-info"
    when :success then "alert-success"
    when :error then "alert-danger"
    when :alert then "alert-warning"
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>
<div class='row'>
<div class='col-xs-12'>
<%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
<div class="form-group">
<div class="control-label col-sm-2">
<%= f.label :title %>
</div>
<div class="col-sm-8">
<%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true %>
</div>
</div>
<div class="form-group">
<div class="control-label col-sm-2">
<%= f.label :description %>
</div>
<div class="col-sm-8">
<%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Body of article" %>
</div>
</div>
<div class="form-group">
<div class="col-xs-4 col-xs-offset-4">
<%= f.submit class: 'btn btn-primary btn-lg' %>
</div>
</div>
<% end %>
<div class="col-xs-4 col-xs-offset-4">
[ <%= link_to "Cancel request and return to articles listing", articles_path %> ]
</div>
</div>
</div>

app/views/articles/edit.html.erb
    <div class="jumbotron hero">
        <div class="container">
            
                <div class="col-xs-12 get-it">
                <h1 align="center">Edit Article <%= @article.id%></h1>
             
                    <%= render 'form' %>
                    
                 </div>
            
        </div>
    </div>
    
<%= render 'layouts/testimonials' %>  
<%= render 'layouts/features' %>

app/views/articles/index.html.erb
    <div class="jumbotron hero">
        <div class="container" style="background-color:white;">
            
                
            
                    <h1 align="center">Listing all articles</h1>
<% @articles.each do |article| %>
<div class="row">
<div class="col-xs-8 col-xs-offset-2">
<div class="well well-lg">
<div class="article-title">
<%= link_to article.title, article_path(article) %>
</div>
<div class="article-body">
<%= truncate(article.description, length: 100) %>
</div>
<div class="article-actions">
<%= link_to "Edit this article", edit_article_path(article), class: "btn btn-xs btn-primary" %>
<%= link_to "Delete this article", article_path(article), method: :delete,
data: { confirm: "Are you sure you want to delete the article?"},
class: "btn btn-xs btn-danger" %>
</div>
</div>
</div>
</div>
<% end %>

        </div>
</div>


<%= render 'layouts/testimonials' %>  
<%= render 'layouts/features' %>
 

app/views/articles/new.html.erb
    <div class="jumbotron hero">
        <div class="container">
            
                <div class="col-xs-12 get-it">
                <h1 style=" text-align:center;">Create new article</h1>
             
                    <%= render 'form' %>
                    
                 </div>
            
        </div>
    </div>
    
<%= render 'layouts/testimonials' %>  
<%= render 'layouts/features' %>
 

app/views/articles/show.html.erb
    <div class="jumbotron hero">
<div class="container post">
        <div class="row">
            <div class="col-md-6 post-title">
                Title:<h1> <%= @article.title %></h1>
                     <%= link_to "Edit Article", edit_article_path, :class => "btn btn-primary" %>&nbsp;&nbsp;
                <%= link_to "Back to Articles", articles_path, :class => "btn btn-default" %>
                </br>
            </br>
                <p class="author"><strong>author: user</strong> <span class="text-muted">Date Stamp HERE</span></p>
            </div>
            <div class="col-md-6 col-md-offset-0 post-body"style="color:white;text-shadow:1px 1px #000;">
                
                <h4>Description:
                </h4><p>   <%= @article.description %>
                </p>
                <p>Sed mollis, urna eu tempus facilisis, diam tellus aliquam tortor, et vestibulum ante quam non justo. Nullam luctus rutrum mattis. Maecenas in pharetra mi, vel mollis odio. </p>
                <figure><%= image_tag 'logo.svg', class:'small-image'%>
                    <figcaption>Praesent sed convallis nisi </figcaption>
                </figure>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sem quam, scelerisque vitae sem non, ornare condimentum leo. Vivamus eros tortor, tincidunt et viverra ac, gravida eu augue. Interdum et malesuada fames ac ante ipsum primis
                 </p>
            </div>
        </div>
    </div>

</div>


<%= render 'layouts/testimonials2' %>  
<%= render 'layouts/features' %>
 

app/views/layouts/_features.html.erb
<section class="features">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <h2>Fantastic Features</h2>
                    <p>Morbi non mauris massa. Duis elit mauris, malesuada nec suscipit ac, bibendum sed augue. Maecenas condimentum magna gravida, laoreet nunc sed, euismod sem. </p>
                </div>
                <div class="col-md-6">
                    <div class="row icon-features">
                        <div class="col-xs-4 icon-feature"><span class="glyphicon glyphicon-cloud"></span>
                            <p>Cloud-ready </p>
                        </div>
                        <div class="col-xs-4 icon-feature"><span class="glyphicon glyphicon-piggy-bank"></span>
                            <p>Saves You Money</p>
                        </div>
                        <div class="col-xs-4 icon-feature"><span class="glyphicon glyphicon-fire"></span>
                            <p>Fire Proof</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <%= link_to root_path, class: "navbar-brand navbar-link" do %>
                <%= image_tag 'logo.svg' %> - ALPHA BLOG - <% end %>
                <button class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navcol-1"><span class="sr-only">Toggle navigation</span><span></span><span></span><span></span><i class="fa fa-navicon"></i> </button>
            </div>
            <div class="collapse navbar-collapse" id="navcol-1">
                <ul class="nav navbar-nav navbar-right">
                    
                    <li role="presentation"><%= link_to "Blog", articles_path %></li>
                    <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">Actions <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><%= link_to "Create New Article", new_article_path %></li>
                            
                        </ul>
                    </li>
                    <li role="presentation"><%= link_to "Contact", contact_path %></li>
                </ul>
            </div>
        </div>
    </nav>

app/views/layouts/_testimonials.html.erb
<section class="testimonials">
        <h2 class="text-center">People Love It!</h2>
        <blockquote>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
            <footer>Famous tech website</footer>
        </blockquote>
    </section>

app/views/layouts/_testimonials2.html.erb
 <section class="testimonials">
        <h2 class="text-center">Did we mention? People Love It!</h2>
        <blockquote>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
            <footer>Famous tech website</footer>
        </blockquote>
    </section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Alpha Blog - migSig Development</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>
<header>
    
              <%= render 'layouts/navigation' %>
    <div class="container"><%= render 'shared/messages' %>
      </div>
</header>
    
   
<%= yield %> <!--DON"T DELETE-->
   
<footer class="site-footer">
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <h5>migSig Inc. © 2016</h5></div>
                <div class="col-sm-6 social-icons"><a href="https://facebook.com/migsiginc"><span class="fa fa-facebook"></span></a><a href="https://twitter.com/migsig"><span class="fa fa-twitter"></span></a><a href="https://instagram.com/migsig"><span class="fa fa-instagram"></span></a></div>
            </div>
        </div>
        <div></div>
    </footer>
</body>
</html>

app/views/pages/contact.html.erb
    <div class="jumbotron hero">
        <div class="container">
            <div class="row">
                
                <div class="col-xs-12 ">
                    <h1>Contact Us</h1>
                    <p>Pick your pleasure:</p>
                    <p><a class="btn btn-primary btn-lg" role="button" href="http://twitter.com/migsig"><span class="fa fa-twitter"></span> Twitter</a><a class="btn btn-success btn-lg" role="button" href="https://instagram.com/migsig"><span class="fa fa-instagram"></span> Instagram</a></p>
                </div>
            </div>
        </div>
    </div>
<%= render 'layouts/testimonials2' %>  
<%= render 'layouts/features' %>
    

app/views/pages/home.html.erb
    <div class="jumbotron hero">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-lg-push-6 col-md-4 col-md-push-7 phone-preview">
                    <div class="iphone-mockup"><%= image_tag 'iphone.svg', class:"visible-md-inline hidden-xs hidden-lg device"%> 
                        <div class="screen"><%= image_tag 'screen.png'%></div>
                    </div>
                    <div class="imac-mockup"><%= image_tag 'imac.svg', class: "hidden-xs hidden-sm hidden-md device" %>
                        <div class="screen"></div>
                    </div>
                </div>
                <div class="col-lg-6 col-lg-pull-6 col-md-6 col-md-pull-3 get-it">
                    <h1>Digital Design Solutions</h1>
                    <div class="iphone-mockup">
                        <div class="screen"></div>
                    </div>
                    <p>Alpha Blog </p>
                    <p>Here your can create show update delete articles. </p>
                    <p><a class="btn btn-primary btn-lg" role="button" href="#"><span class="fa fa-rocket"></span> Sign Up</a>
<!--                        <a class="btn btn-success btn-lg" role="button" href="#"><span class="fa fa-google"></span> Available on Google Play</a></p>-->
                </div>
            </div>
        </div>
    </div>
<%= render 'layouts/testimonials' %>  
<%= render 'layouts/features' %>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class="row">
    <div class="col-xs-8 col-xs-offset-2">
        <div class="panel panel-danger">      
            
            <div class="panel-heading">
                <h2 class="panel-title"> The following <%= pluralize(obj.errors.count, "error") %> prevented the Article from being saved:
                </h2>
                </br>
                <div class="panel-body">
                <ul>
                    <% obj.errors.full_messages.each do |msg| %>
                    <li style="list-decoration:none;"><%= msg %></li>
                    <%end%>
                   
                </ul>
                </div>
            </div>
        </div>
  </div>
 </div>   
<%end%>     

app/views/shared/_messages.html.erb
 <div class="container">
     <div class="row">
        <% flash.each do |name, msg| %>
    <div class='alert alert-<%= "#{name}" %> fade in'>
       <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= content_tag :div,msg, :id =>"flash_#{name}" if msg.is_a?(String) %>
    </div>
<!--         <ul><li><%= msg %></li></ul>-->
  <% end %>
     </div>
</div>